// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Delivery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.Models.Order", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DatePickup")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_pickup");

                    b.Property<string>("RecCity")
                        .HasColumnType("text")
                        .HasColumnName("rec_city");

                    b.Property<int>("RecHome")
                        .HasColumnType("integer")
                        .HasColumnName("rec_home");

                    b.Property<string>("RecStreet")
                        .HasColumnType("text")
                        .HasColumnName("rec_street");

                    b.Property<string>("SendCity")
                        .HasColumnType("text")
                        .HasColumnName("send_city");

                    b.Property<int>("SendHome")
                        .HasColumnType("integer")
                        .HasColumnName("send_home");

                    b.Property<string>("SendStreet")
                        .HasColumnType("text")
                        .HasColumnName("send_street");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("orders", "info");
                });
#pragma warning restore 612, 618
        }
    }
}
